### ISSUE TITLE
hardhat-anvil does not allow connecting to anvil node running in docker

### ISSUE THREAD

**Issue by mshakeg** [foundry-rs/hardhat#110]
I'm trying to run a hardhat project that uses an anvil node in docker. So I set the url for the anvil network in the hardhat config to `"http://anvil-1:8545/"` where `anvil-1` is the name of the service that contains the anvil node, instead of setting it to `http://127.0.0.1:8545/` as this is required for the hardhat service to connect to the `anvil-1` service.

Below is the error that the hardhat service fails with:

```
Error in plugin @foundry-rs/hardhat-anvil: Anvil network only works with localhost
2023-10-03 10:14:05 NomicLabsHardhatPluginError: Anvil network only works with localhost
2023-10-03 10:14:05     at Function.getCheckedArgs (/app/node_modules/.pnpm/@foundry-rs+hardhat-anvil@0.1.7_@nomiclabs+hardhat-ethers@2.2.3_ethereum-waffle@3.4.4_ethers@6.7.0_hardhat@2.17.3/node_modules/@foundry-rs/hardhat-anvil/src/anvil-service.ts:85:13)
2023-10-03 10:14:05     at async Function.create (/app/node_modules/.pnpm/@foundry-rs+hardhat-anvil@0.1.7_@nomiclabs+hardhat-ethers@2.2.3_ethereum-waffle@3.4.4_ethers@6.7.0_hardhat@2.17.3/node_modules/@foundry-rs/hardhat-anvil/src/anvil-service.ts:98:18)
2023-10-03 10:14:05     at async handlePluginTask (/app/node_modules/.pnpm/@foundry-rs+hardhat-anvil@0.1.7_@nomiclabs+hardhat-ethers@2.2.3_ethereum-waffle@3.4.4_ethers@6.7.0_hardhat@2.17.3/node_modules/@foundry-rs/hardhat-anvil/src/index.ts:207:24)
2023-10-03 10:14:05     at async Environment._runTaskDefinition (/app/node_modules/.pnpm/hardhat@2.17.3_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:14)
2023-10-03 10:14:05     at async Environment.run (/app/node_modules/.pnpm/hardhat@2.17.3_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:14)
2023-10-03 10:14:05     at async main (/app/node_modules/.pnpm/hardhat@2.17.3_ts-node@10.9.1_typescript@4.9.5/node_modules/hardhat/src/internal/cli/cli.ts:280:7)
```

**Comment by mattsse** [comment]
try `--host "0.0.0.0"`

**Comment by mshakeg** [comment]
@mattsse that works but this issue seems to be that `hardhat-anvil` isn't allowing the anvil host in the `url` network to be other than `localhost` so I currently just disabled `hardhat-anvil`

The issue is likely [here](https://github.com/foundry-rs/hardhat/blob/726dad92b88d83d8e9858163b0ec4ac168f601d8/packages/hardhat-anvil/src/anvil-service.ts#L84)

**Comment by mattsse** [comment]
I see, do you want to submit a fix for that?

**Comment by mshakeg** [comment]
@mattsse sure in a bit
